// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

//const SUPABASE_URL = "https://pmjhsddknpkdxfbxtxrz.supabase.co";
const SUPABASE_URL = "https://tglohosjdjqmonnlvawe.supabase.co";
//const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtamhzZGRrbnBrZHhmYnh0eHJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMzE5NjcsImV4cCI6MjA3MDYwNzk2N30.1Ywq40hbd5teBxmfnsHimgvCtCuUU-XqAwhnxvAT7Lo";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRnbG9ob3NqZGpxbW9ubmx2YXdlIiwicm9zZSI6ImFub24iLCJpYXQiOjE3NTU5ODg2MTUsImV4cCI6MjA3MTU2NDYxNX0.H7Hfi2uk_5G76gVIFQC1Ewbcj42XSvejp5GLpV3ryrc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Example: Skip authentication for static files
export function middleware(req) {
  if (
    req.nextUrl.pathname.startsWith('/manifest.json') ||
    req.nextUrl.pathname.startsWith('/favicon') ||
    req.nextUrl.pathname.startsWith('/icon-')
  ) {
    return NextResponse.next();
  }
  // ...existing authentication or other logic...
}

// Fix: Remove or replace imports that are not supported in Edge Functions

// Remove or comment out the following lines if you are deploying to Vercel Edge Functions:
//
// import type { SomeType } from './types';
// import { NextRequest, NextResponse } from 'next/server';
//
// Edge Functions do not support 'next/server' or local type imports.