// This file is automatically generated. Do not edit it directly.
//import { createClient } from '@supabase/supabase-js';

//const SUPABASE_URL = "https://pmjhsddknpkdxfbxtxrz.supabase.co";
const SUPABASE_URL = "https://tglohosjdjqmonnlvawe.supabase.co";
//const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtamhzZGRrbnBrZHhmYnh0eHJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMzE5NjcsImV4cCI6MjA3MDYwNzk2N30.1Ywq40hbd5teBxmfnsHimgvCtCuUU-XqAwhnxvAT7Lo";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRnbG9ob3NqZGpxbW9ubmx2YXdlIiwicm9zZSI6ImFub24iLCJpYXQiOjE3NTU5ODg2MTUsImV4cCI6MjA3MTU2NDYxNX0.H7Hfi2uk_5G76gVIFQC1Ewbcj42XSvejp5GLpV3ryrc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

//export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
//  auth: {
//    storage: localStorage,
//    persistSession: true,
//    autoRefreshToken: true,
//  }
// });

// --- FIX: Remove Supabase client usage and localStorage from Edge middleware ---
// Edge Functions do not support localStorage or browser APIs.
// Supabase client is not needed in middleware for static file skipping.

export const config = {
  matcher: [
    '/((?!api|_next/static|_next/image|favicon.ico|manifest.json|favicon|icon-|assets|service-worker.js|robots.txt|poker-logo.png|Poker_01.png|Poker_02.png|Poker_03.png|Poker_04.png|Poker_05.png|Poker_06.png|placeholder.svg|screenshot-1.png).*)'
  ],
};

export default function middleware(request: Request) {
  // Do not return anything for normal requests.
  // Let Vercel handle routing.
}