// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pmjhsddknpkdxfbxtxrz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtamhzZGRrbnBrZHhmYnh0eHJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMzE5NjcsImV4cCI6MjA3MDYwNzk2N30.1Ywq40hbd5teBxmfnsHimgvCtCuUU-XqAwhnxvAT7Lo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});